#!/bin/bash
#
# +--------------------------------------------------------------------------------+
# | Copyright (C) 2013 Kuboosoft                                                   |
# |                                                                                |
# | Este programa es Software Libre; Puedes distribuirlo y/o                       |
# | modificarlo bajo los términos de la GNU General Public License                 |
# | como está publicada por la Free Software Foundation; cualquier                 |
# | versión 3 de la Licencia, o (opcionalmente) cualquier versión                  |
# | posterior. http://www.gnu.org/licenses/lgpl.html                               |
# |                                                                                |
# | Este programa es distribuido con la esperanza de que sea útil,                 |
# | pero SIN NINGUNA GARANTÍA. Vea la GNU General Public License                   |
# | para más detalles.                                                             |
# +--------------------------------------------------------------------------------+
# | Este código ha sido diseñado,escrito y mantenido por Kuboode y David Vásquez   |
# | Cualquier pregunta, comentario o consejo sobre este código                     |
# | debe dirigirse a:                                                              |
# | http:www.kuboosoft.blogspot.com                                                |
# +--------------------------------------------------------------------------------+

xhost +

if [ `getconf LONG_BIT` = "64" ]
then
    echo "Este es un sistema de 64-bit"
yad --class="ATENCIÓN" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/acciones/add.png" --image-on-top --entry --hide-text --title="PostInstallerF" --text="Authentication is required, please Insert your administrative password :" | su root -c "bash /usr/bin/postinstallerf/Postinstaller64.sh"
else
    echo "Este es un sistema de 32-bit"
yad --class="ATENCIÓN" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/acciones/add.png" --image-on-top --entry --hide-text --title="PostInstallerF" --text="Authentication is required, please Insert your administrative password :" | su root -c "bash /usr/bin/postinstallerf/Postinstaller32.sh"
fi


#identificando tipo de usuario

noti3=$(loginctl show-session $XDG_SESSION_ID | cut -d= -f2 | tail -n 1); echo "noti3 = $noti3"
