#!/bin/bash
#
# +--------------------------------------------------------------------------------+
# | Copyright (C) 2014 Kuboosoft                                                   |
# |                                                                                |
# |This program is free software; You can distribute it and / or                   |
# |modify it under the terms of the GNU General Public License                     |
# |as published by the Free Software Foundation; any                               |
# |version 3 of the License, or (optionally) any version                           |
# |later. http://www.gnu.org/licenses/gpl-3.0.html                                 |
# |This program is distributed in the hope that it will be useful,                 |
# |but WITHOUT ANY WARRANTY. See the GNU General Public License                    |
# |for details.                                                                    |
# +--------------------------------------------------------------------------------+
# |This code is designed, written and maintained by David Vasquez    		   |
# |Any questions, comments or advice on this code                                  |
# |should be addressed to:                                                         |
# |https://plus.google.com/communities/118230919321773121406                       |
# +--------------------------------------------------------------------------------+


export LC_TIME=en_US

check_up= yum -e0 -d0 check-update > /tmp/yum.results.XXXXXX

YUMHIS=`yum history | grep -n "U" | head -n 1 | cut -f3 -d'|' | sed 's/^ //g' | cut -f1 -d' '`

date3=$(date +"%b %d")
date2=$(date +%D)
number=$( wc -l /tmp/yum.results.XXXXXX | awk '{print $1}' ); echo number=$number

log=$(cat -T /var/log/yum.log | grep -e "`date "+%b %d"`" ) 

WORK2=/tmp/yum.results.XXXXXX

culito=$( awk '{print $1, "	", $2, "	", $3}' $WORK2 ); echo culito=$culito


# If there are updates available, Ask to user if want update 

if [ -s $WORK2 ] && [ -z $YUMHIS ]; then  

	if [ $(echo $LANG | cut -b1-2) = "es" ]; then

yad --width=450 --height=300 \
				--center \
                                --title="Hay $number actualizaciones disponibles este $date2" \
				--window-icon=logviewer \
                                --image-on-top --image="/usr/share/icons/updatep2.png" \
				--text="Desea usted actualizar?" \
				--list \
				--column=Paquete --column=Version --column=Repositorio $culito \
                                --button="Actualizar Ahora:0" --button="Actualizar Despues:1" 

if [ $? -eq 0 ]; then

yum -y --exclude=kernel* update | pv 2>&1 | yad --center --class="Updating" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/updatep2.png" --image-on-top --width="435" --height="300" --title "Updating the system" --text="Por favor espere.... Cierre cuando los procesos terminen." --list --column="Lista de Progreso" --button="Cancelar (No recomendado):0" --button="Cerrar:1"


if [ $? -eq 0 ]; then
	pkill -SIGKILL -u root -o yum
else
	echo "thanks"

yum-complete-transaction --cleanup-only -y | pv -n 2>&1 | yad --center --class="Installing" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/icoinstall2.png" --image-on-top --progress --title "Completando Instalaciones pendientes" --text="Por favor espere...." --pulsate --auto-close ---width="435" --height="300"

yad --center --title="Log viewer updates" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/logview.png" --image-on-top --list --width="435" --height="300" --text="Content of yum updates" --column=Month --column=Date --column=Time --column=Status --column=Package $log --button="Close:1"
	fi
	exit 0 

else
	echo "thanks"
	fi
	exit 0 

else


yad --width=450 --height=300 \
				--center \
                                --title="There are $number updates available at $date2" \
				--window-icon=logviewer \
                                --image-on-top --image="/usr/share/icons/updatep2.png" \
				--text="Do you want update?" \
				--list \
				--column=Package --column=Version --column=Repository $culito \
                                --button="Update Now:0" --button="Update Later:1"

if [ $? -eq 0 ]; then

yum -y --exclude=kernel* update | pv 2>&1 | yad --center --class="Updating" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/updatep2.png" --image-on-top --width="435" --height="300" --title "Updating the system" --text="Please wait.... Close when the process is finished." --list --column="Progress List" --button="Cancel (Not recommended):0" --button="Close:1"

if [ $? -eq 0 ]; then
	pkill -SIGKILL -u root -o yum
else
	echo "thanks"
yum-complete-transaction --cleanup-only -y | pv -n 2>&1 | yad --center --class="Installing" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/icoinstall2.png" --image-on-top --progress --title "Completando Instalaciones pendientes" --text="Por favor espere...." --pulsate --auto-close ---width="435" --height="300"

yad --center --title="Log viewer updates" --window-icon="/usr/share/icons/acciones/topicon.png" --image="/usr/share/icons/logview.png" --image-on-top --list --width="435" --height="300" --text="Content of yum updates" --column=Month --column=Date --column=Time --column=Status --column=Package $log --button="Close:1"
	fi
	exit 0 

else
	echo "thanks"
	fi
	exit 0 

   fi

# Clean yum.results
cat /dev/null > /tmp/yum.results.XXXXXX
 else
echo 'no updates'
fi



